blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls'))
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("register/", views.register_user, name="register"),
    path("post/", views.create_post, name="create_post"),
    path("post/edit/<int:pk>", views.edit_post, name="edit_post"),
    path("post/delete/<int:pk>", views.delete_post, name="delete_post"),
    path("post/<int:pk>", views.post_page, name="post"),
    path("comment/delete/<int:pk>", views.remove_comment, name="remove_comment"),
]

core/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.db.models.signals import post_save
class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    
    # Add your custom fields here
    # For example:
    # bio = models.TextField(blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email



# Create your models here.
class BlogPost(models.Model):
    title=models.CharField(max_length=70)
    content=models.TextField()
    author = models.ForeignKey(CustomUser,on_delete=models.CASCADE,default=None)
    created_at=models.DateTimeField(auto_now_add=True)
    image=models.ImageField(upload_to='uploads/posts/',default="media/uploads/posts/4.png")
    # video=models.FieldFile(upload_to='uploads/posts/videos')
    def __str__(self):
        return self.title

    def get_sub_content(self):
        if len(self.content)>25:
            return f'{self.content[0:10]}...'
        else:
            return self.content
    
class Comment(models.Model):
   post=models.ForeignKey(BlogPost,related_name="comments",on_delete=models.CASCADE,default=None)
   author = models.ForeignKey(CustomUser,on_delete=models.CASCADE,default=None)
   content=models.TextField()
   created_at=models.DateTimeField(auto_now_add=True)

core/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Comment, CustomUser,BlogPost

# forms.py




		
class SignUpForm(UserCreationForm):
	email = forms.EmailField(
        label='Email',
        widget=forms.EmailInput(attrs={'class': 'w-full px-3 py-2 border rounded-md focus:outline-none focus:border-blue-500'})
    )
	first_name = forms.CharField(
        label='First Name',
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'w-full px-3 py-2 border rounded-md focus:outline-none focus:border-blue-500'})
    )
	last_name = forms.CharField(
        label='Last Name',
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'w-full px-3 py-2 border rounded-md focus:outline-none focus:border-blue-500'})
    )

	class Meta:
		model = CustomUser
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

	def __init__(self, *args, **kwargs):
		super(SignUpForm, self).__init__(*args, **kwargs)

		self.fields['username'].widget.attrs['class'] = 'w-full px-3 py-2 border rounded-md focus:outline-none focus:border-blue-500'
		self.fields['username'].widget.attrs['placeholder'] = 'User Name'
		self.fields['username'].label = ''
		self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

		self.fields['password1'].widget.attrs['class'] = 'w-full px-3 py-2 border rounded-md focus:outline-none focus:border-blue-500'
		self.fields['password1'].widget.attrs['placeholder'] = 'Password'
		self.fields['password1'].label = ''
		self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

		self.fields['password2'].widget.attrs['class'] = 'w-full px-3 py-2 border rounded-md focus:outline-none focus:border-blue-500'
		self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
		self.fields['password2'].label = ''
		self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'


class BlogPostForm(forms.ModelForm):
	class Meta:
		model=BlogPost	
		fields=['title','content','image']
		widgets={
			'title':forms.TextInput(attrs={'class':'w-full px-3 py-2 border rounded-md focus:outline-none focus:border-blue-500'}),
			'content':forms.Textarea(attrs={'class':'w-full px-3 py-2 border rounded-md focus:outline-none focus:border-blue-500'}),
			}
class CommentForm(forms.ModelForm):
	class Meta:
		model=Comment	
		fields=["content"]
		widgets={
			'content':forms.TextInput(attrs={'class':'w-full px-3 py-2 w-[250px] border rounded-md focus:outline-none focus:border-blue-500'}),
			}



		


		

	

core/views.py
import os
from django import urls
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import  SignUpForm, BlogPostForm, CommentForm
from .models import BlogPost, Comment
from django.db.models import Q
from .utils import send_email_to_client
login_url = "/login"


# Create your views here.
@login_required(login_url=login_url)
def home(request):

    is_home = True
    posts = BlogPost.objects.all()
    # send_email_to_client()
    if request.method == "POST":
        searched = request.POST.get("search")
        if searched is not None:
            posts = BlogPost.objects.filter(
                Q(title__icontains=searched) | Q(content__icontains=searched)
            )
    return render(request, "index.html", {"posts": posts, "is_home": is_home})


def login_user(request):
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")
        user = authenticate(email=email, password=password)
        if user is not None:
            messages.success(request, f"You are logged in")
            login(request, user)
            return redirect("home")
        else:
            messages.error(request, "Failed to login! please  try again")
            return redirect("home")

    return render(request, "login.html")


def logout_user(request):
    logout(request)
    messages.warning(request, f"You are logged out ")
    return redirect("home")


def register_user(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password1"]
            user = authenticate(email=email, password=password)
            login(request, user)
            messages.success(request, "You Have Successfully Registered! Welcome!")
            return redirect("home")
        else:
            for error in form.error_messages.values():
                messages.error(request, f"{error}")
            return redirect("register")

    else:
        form = SignUpForm()
        return render(request, "register.html", {"form": form})


@login_required(login_url=login_url)
def create_post(request):
    if request.method == "POST":
        form = BlogPostForm(request.POST, request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            return redirect("home")
        else:
            for error in form.error_messages.values():
                messages.error(request, f"{error}")

            return redirect("home")
    form = BlogPostForm()
    return render(request, "create_post.html", {"form": form})


@login_required(login_url=login_url)
def edit_post(request, pk):
    post = get_object_or_404(BlogPost, id=pk)
    if request.method == "POST":
        post.title = request.POST.get("title")
        post.content = request.POST.get("content")
        if len(request.FILES) != 0:
            if len(post.image) > 0:
                os.remove(post.image.path)
            post.image = request.FILES.get("image")
        post.save()
        return redirect("home")
    return render(request, "edit_post.html", {"post": post})


@login_required(login_url=login_url)
def post_page(request, pk):
    post = get_object_or_404(BlogPost, id=pk)
    comments = Comment.objects.filter(post__id=post.id).order_by('-created_at')

  
    if request.method == "POST":
        form = CommentForm(request.POST)
        
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.post = post
            new_comment.save()
            new_comment.content = ""
       
            return redirect(f'/post/{post.id}')
    form = CommentForm()

    return render(
        request, "post_page.html", {"comments": comments, "post": post, "form": form}
    )


def delete_post(request, pk):
    post = get_object_or_404(BlogPost, id=pk)
    post.delete()
    if len(post.image) > 0:
        os.remove(post.image.path)
    return redirect("home")


def remove_comment(request,pk):

    comment=get_object_or_404(Comment, id=pk)
    if comment.author.username ==request.user.username:
        print(comment.post.id)
        comment.delete()
        return redirect(f'/post/{comment.post.id}')
    else:
        messages.error(request,"You cannot delete this comment")
        return redirect(f'/post/{comment.post.id}')

core/templates/create_post.html
{% extends "layout.html" %}
{% block title %}Post{% endblock title %}

{% block content %}
<div class="max-w-md mx-auto bg-white rounded-lg overflow-hidden md:max-w-lg">
    <div class="md:flex">
      <div class="w-full px-6 py-8 md:p-8">
        <h2 class="text-center font-semibold text-2xl tracking-wide mb-6">Add Post</h2>
       
        <form method="POST" enctype="multipart/form-data" >
            {% csrf_token %}
            {{form.as_p}}
            <div class="mt-6">
                <button type="submit" class="w-full bg-blue-500 text-white py-2 px-4 rounded-md focus:bg-blue-600 focus:outline-none">Add</button>
              </div>
              
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

core/templates/edit_post.html
{% extends "layout.html" %}
 {% block title %}Edit Post{% endblock title %} 
{% block content %}
<div class="max-w-md mx-auto bg-white rounded-lg overflow-hidden md:max-w-lg">
  <div class="md:flex">
    <div class="w-full px-6 py-8 md:p-8">
      <h2 class="text-center font-semibold text-2xl tracking-wide mb-6">
        Edit Post
      </h2>

      <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
        <p>
          <label for="id_title">Title:</label>
          <input
            type="text"
            value="{{post.title}}"
            name="title"
            class="w-full px-3 py-2 border rounded-md focus:outline-none focus:border-blue-500"
            maxlength="70"
            required
            id="id_title"
          />
        </p>

        <p>
          <label for="id_content">Content:</label>
          <textarea
            name="content"
            cols="40"
           
            rows="10"
            class="w-full px-3 py-2 border rounded-md focus:outline-none focus:border-blue-500"
            required
            id="id_content"
          >{{post.content}}</textarea>
        </p>

        <p>
          <label for="id_image">Image:</label>
          <input
            type="file"
            name="image"
    value="{{post.image}}"
            accept="image/*"
            
            id="id_image"
          />
        </p>
        <p>{{post.image.url}}</p>
        <img src="{{post.image.url}}" alt="image" >
        <div class="mt-6">
          <button
            type="submit"

            class="w-full bg-blue-500 text-white py-2 px-4 rounded-md focus:bg-blue-600 focus:outline-none"
          >
            Edit
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

core/templates/index.html
{% extends "layout.html" %}
{% block title %}Home{% endblock title %}

{% block content %}
<div class="container mx-auto py-8">
    <h1 class="text-3xl font-bold mb-8">All Posts</h1>
    <div class="grid grid-rows-1 w-full justify-center md:grid-rows-2 lg:grid-rows-3 gap-8">
      <!-- Example post item -->
      {% if posts|length == 0 %}
      <h1>No Post to Show</h1>
      {% else %}
{% for post in posts %}
<article class="text-center w-[300px] bg-slate-300  shadow-sm rounded-md m-2 p-4">
    <a href="{% url "post" post.id %}">
      <h2 class="text-xl font-semibold mb-2">{{post.title}}</h2>
      
    </a>
 
   
    <p class="text-gray-700">{{post.get_sub_content}}</p>

</article>
{% endfor %}
        {% endif %}

      
        </div>
      </div>
      <!-- End of example post item -->
  
      <!-- Repeat the above block for each post -->
    </div>
  </div>
  
{% endblock content %}

core/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="shortcut icon"
      href="assets/icons8-favicon-50.png"
      type="image/x-icon"
    />
    <script src="{% static "script.js" %}" defer></script>
    <link rel="stylesheet" href="{% static "style.css" %}">
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include "navbar.html" %} {% for message in messages %} 
    {% if message.tags == "error" %}

    <li  class=" flex justify-between list-none p-3 text-3xl bg-red-500 text-red-950 text-center">
      {{message}}
<div  class="cursor-pointer" id="message-destroy">&times;</div>
</li>

{% elif message.tags == "success" %}
<li id="message"  id="message-destroy" class=" flex justify-between list-none p-3 text-3xl bg-green-500 text-green-950 text-center">
  {{message}}
      <div class="cursor-pointer" id="message-destroy">&times;</div>
    </li>
{% elif message.tags == "warning" %}
<li id="message"  id="message-destroy" class=" flex justify-between list-none p-3 text-3xl bg-yellow-500 text-yellow-950 text-center">
  {{message}}
      <div class="cursor-pointer" id="message-destroy">&times;</div>
    </li>


    {% endif %} 
    
    
    {% endfor %}



     {% block content %}{% endblock content %}
  </body>
</html>

core/templates/login.html
{% extends "layout.html" %}
{% block title %}Login{% endblock title %}

{% block content %}
<div class="max-w-md mx-auto bg-white rounded-lg overflow-hidden md:max-w-lg">
    <div class="md:flex">
      <div class="w-full px-6 py-8 md:p-8">
        <h2 class="text-center font-semibold text-2xl tracking-wide mb-6">Sign In</h2>
        <form method="POST">
          {% csrf_token %}
          <div class="mb-4">
            <label for="email" class="block text-gray-700 text-sm font-bold mb-2">Email</label>
            <input type="text" id="email" name="email" placeholder="Email" class="appearance-none border rounded-md w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
          </div>
          
          <div class="mb-6">
            <label for="password" class="block text-gray-700 text-sm font-bold mb-2">Password</label>
            <input type="password" id="password" name="password" placeholder="********" class="appearance-none border rounded-md w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
          </div>
          <div class="mb-6">
            <button type="submit" class="w-full bg-blue-500 text-white py-2 px-4 rounded-md focus:bg-blue-600 focus:outline-none">Sign In</button>
          </div>
          <p class="text-center text-gray-500 text-sm">
            Not have an account? <a href="{% url "register" %}" class="text-blue-500">Sign up</a>.
          </p>
        </form>
      </div>
    </div>
  </div>
  
{% endblock content %}

core/templates/navbar.html
<nav class="bg-gray-800 py-4">
    <div class="max-w-7xl mx-auto px-4">
      <div class="flex justify-between">
        <!-- Logo -->
        <div class="flex items-center">
          {% comment %} <a href="#" >Your Logo</a> {% endcomment %}
          {% if is_home %}
       <form action="" method="post" >
         {% csrf_token %}
        <input type="text" name="search">
        <button type="submit" class="bg-blue-500 text-white font-bold rounded-md p-2 px-3">search</button>
      </form>
      {% endif %}
        </div>
       
        <!-- Navigation Links -->
        <div class="hidden md:flex space-x-4">
          <a href="{% url 'home' %}" class="text-white hover:text-gray-300">Home</a>
          {% if user.is_authenticated %}
          
          <a href="{% url 'logout' %}" class="text-white hover:text-gray-300">Logout</a>
      {% else %}
      <a href="{% url 'login' %}" class="text-white hover:text-gray-300">Login</a>
          {% endif %}

          <a href="{% url "create_post" %}" class="text-white hover:text-gray-300">Post</a>
   
        </div>
      
        <!-- Mobile Menu Button -->
        <div class="md:hidden flex items-center">
          <button id="mobile-menu-btn" class="text-white focus:outline-none">
            <svg class="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
            </svg>
          </button>
        </div>
      </div>
    </div>
    
    <!-- Mobile Menu -->
    <div id="mobile-menu" class="md:hidden bg-gray-800">
      <div class="px-2 py-3 space-y-2">
        {% if user.is_authenticated %}
          
        <a href="{% url 'logout' %}" class="text-white hover:text-gray-300">Logout</a>
    {% else %}
    <a href="{% url 'login' %}" class="text-white hover:text-gray-300">Login</a>
        {% endif %}
        <a href="{% url "home" %}" class="block text-white hover:text-gray-300">Home</a>
        <a href="{% url "create_post" %}" class="text-white hover:text-gray-300">Post</a>
   
      </div>
    </div>
  </nav>
  

core/templates/post_page.html
{% extends "layout.html" %}
{% block title %}Post {{post.id}}{% endblock title %}

{% block content %}
<div class="container mx-auto py-8">
    <div class="flex flex-col justify-center w-full items-center">
      <!-- Example post item -->
      
<img src="{{post.image.url}}" width="200" alt="..." >
      <h2 class="text-xl font-semibold">{{post.title}}</h2>
      <p class="text-gray-700">{{post.content}}</p>
      <div class="flex justify-between">
        <a href="{% url "edit_post" post.id %}">
        
            <button
            type="button"
        
            class=" bg-blue-500 m-2 min-w-[80px] text-white py-2 px-4 rounded-md focus:bg-blue-600 focus:outline-none"
            >
            Edit
          </button>
        </a>
        <a href="{% url "delete_post" post.id %}">
          <button
          type="button"
        
          class=" bg-red-500 m-2 min-w-[80px] text-white py-2 px-4 rounded-md focus:bg-red-600 focus:outline-none"
          >
          Delete
              </button>
        </a>
      </div>
        
      
        </div>
  
      <section class="flex flex-col items-start ">
          {% if comments %}
{% for comment in  comments %}

<article class ="shadow-lg my-1 rounded-sm p-2 w-full ">
<h1 class="font-bold  ">{{comment.author.username}}</h1>
<p class="text-sm">{{comment.content}}</p>
{% if user.username == comment.author.username %}

<p class="text-end"><a href="{% url "remove_comment" comment.id %}"><button class=" bg-red-500 m-2  min-w-[80px] text-white shadow-md  py-2 px-4 font-bold rounded-md focus:bg-red-600 focus:outline-none" >Delete</button></a> </p>
{% endif %}
  
</article>
{% endfor %}
          
          {% endif %}
      </section>
       <form method="POST" class="mx-5">
{% csrf_token %}
        {{form}}
        
        <button 
        class=" bg-blue-500 m-2 min-w-[80px] text-white py-2 px-4 rounded-md focus:bg-blue-600 focus:outline-none"
               
        type="submit">Add Comment</button>
       </form>
      </div>
      
    </div>
  </div>
  
{% endblock content %}

core/templates/register.html
{% extends "layout.html" %}
{% block title %}Register{% endblock title %}

{% block content %}
<div class="max-w-md mx-auto bg-white rounded-lg overflow-hidden md:max-w-lg">
    <div class="md:flex">
      <div class="w-full px-6 py-8 md:p-8">
        <h2 class="text-center font-semibold text-2xl tracking-wide mb-6">Sign Up</h2>
       
        <form method="POST" >
            {% csrf_token %}
            {{form.as_p}}
            <div class="mt-6">
                <button type="submit" class="w-full bg-blue-500 text-white py-2 px-4 rounded-md focus:bg-blue-600 focus:outline-none">Sign Up</button>
              </div>
              <p class="text-center text-gray-500 text-sm">
                Already have an account? <a href="{% url "login" %}" class="text-blue-500">Sign in</a>.
              </p>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}